name: sakiengine
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.24

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Add flutter_animate dependency (using specific version constraint)
  flutter_animate: ^4.5.0 # Use a specific constraint like ^4.0.0 or newer

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  window_manager: ^0.5.1
  flutter_screenutil: ^5.9.3
  provider: ^6.1.4
  path: ^1.9.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  hotkey_manager: ^0.2.3
  flutter_avif: ^3.0.0
  flutter_svg: ^2.0.10
  media_kit: ^1.1.10
  media_kit_video: ^1.1.10
  media_kit_libs_android_video: ^1.3.7
  media_kit_libs_ios_video: ^1.1.4
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_windows_video: ^1.0.10
  media_kit_libs_linux: ^1.1.4
  just_audio: ^0.9.46
  just_audio_media_kit: ^2.1.0
  flutter_steamworks: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  rename: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/default_game.txt
    - assets/fonts/
    - assets/GameScript_en/
    - assets/GameScript_en/labels/
    - assets/GameScript_en/configs/
    - assets/GameScript/
    - assets/GameScript/labels/
    - assets/GameScript/configs/
    - assets/GameScript_zh-Hant/
    - assets/GameScript_zh-Hant/labels/
    - assets/GameScript_zh-Hant/configs/
    - assets/GameScript_ja/
    - assets/GameScript_ja/labels/
    - assets/GameScript_ja/configs/
    - assets/i18n/
    - assets/Assets/
    - assets/Assets/music/
    - assets/Assets/images/
    - assets/Assets/images/cg/
    - assets/Assets/images/cg/cg_cp1_1/
    - assets/Assets/images/cg/cg_tree/
    - assets/Assets/images/cg/cg_dog/
    - assets/Assets/images/cg/cg_cp1_5/
    - assets/Assets/images/cg/cg_cp1_2/
    - assets/Assets/images/cg/cg_cp0_q2/
    - assets/Assets/images/cg/cg_cp1_ls/
    - assets/Assets/images/cg/cg_cp1_3/
    - assets/Assets/images/cg/cg_cp0_1/
    - assets/Assets/images/backgrounds/
    - assets/Assets/images/items/
    - assets/Assets/images/characters/
    - assets/Assets/images/characters/story1/
    - assets/Assets/images/characters/story1/emoji/
    - assets/Assets/images/characters/story1/pose/
    - assets/Assets/voice/
    - assets/Assets/gui/
    - assets/Assets/movies/
    - assets/Assets/fonts/
    - assets/Assets/sound/
    - pubspec.yaml

  shaders:
    # 着色器必须在这里单独声明
    - assets/shaders/dissolve.frag

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SourceHanSansCN
      fonts:
        - asset: assets/fonts/SourceHanSansCN-Bold.ttf
          weight: 700
    - family: ChillJinshuSongPro_Soft
      fonts:
        - asset: assets/Assets/fonts/ChillJinshuSongPro_Soft.otf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  windows:
    generate: true
    image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"
